SajChat/SajChat/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.views import LogoutView

from core.views import(
    home_screen_view,
    chat_view,
    sentMessages,
    receivedMessages,
    chatNotification,
)

from account.views import(
    register_view,
    login_view,
    logout_view,
    account_search_view,
)


urlpatterns = [
    path('',home_screen_view, name='home'),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('search/', account_search_view, name='search'),
    path('chat/<str:pk>', chat_view, name='chat'),
    path('sent_msg/<str:pk>', sentMessages, name='sent_msg'),
    path('rec_msg/<str:pk>', receivedMessages, name='rec_msg'),
    path('notification/', chatNotification, name = "notification"),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SajChat/account/urls.py
from django.urls import path

from account.views import (
	account_view,
    edit_account_view,
)

app_name = 'account'

urlpatterns = [
	path('<user_id>/', account_view, name="view"),
	path('<user_id>/edit/', edit_account_view, name="edit"),
]

SajChat/core/models.py
from django.db import models
from account.models import Account

class ChatMessage(models.Model):
    body = models.TextField()
    msg_sender = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="msg_sender")
    msg_receiver = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="msg_receiver")
    seen = models.BooleanField(default=False)


    def __str__(self):
        return self.body
    

SajChat/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from account.models import Account, Friend
from core.form import ChatMessageForm
from core.models import ChatMessage
from django.http import JsonResponse
import json


@login_required(login_url='/login/')
def home_screen_view(request, *args, **kwargs):
    user = Account.objects.get(username=request.user)
    friends = user.friends.all()
    context = {"user": user, "friends": friends}
    return render(request, "core/home.html", context)

@login_required(login_url='/login/')
def chat_view(request, pk):
    friend = Friend.objects.get(profile_id=pk)
    user = request.user
    profile = Account.objects.get(id=friend.profile.id)
    sent_chats = ChatMessage.objects.filter(msg_sender=user, msg_receiver=profile)
    received_chats =ChatMessage.objects.filter(msg_sender=profile, msg_receiver=user)
    received_chats.update(seen=True)
    chats = sent_chats.union(received_chats)
    form = ChatMessageForm()
    if request.method == "POST":
        form = ChatMessageForm(request.POST)
        if form.is_valid():
            chat_message = form.save(commit=False)
            chat_message.msg_sender = user
            chat_message.msg_receiver = profile
            chat_message.save()
            return redirect("chat", pk=friend.profile.id)
    context = {"friend": friend, "form": form,"user":user, "profile": profile, "chats": chats, "count": received_chats.count() }
    if user == profile:
        return redirect('home')
    
    friend_profile = Account.objects.get(id=pk)
    if not user.friends.filter(profile=friend_profile).exists():
        friend_instance, created = Friend.objects.get_or_create(profile=friend_profile)
        user.friends.add(friend_instance)

    return render(request, "core/chat.html", context)

@login_required(login_url='/login/')
def sentMessages(request, pk):
    user = request.user
    friend = Friend.objects.get(profile_id=pk)
    profile = Account.objects.get(id=friend.profile.id)
    data = json.loads(request.body)
    new_chat = data["msg"]
    new_chat_message = ChatMessage.objects.create(body=new_chat, msg_sender=user ,msg_receiver=profile, seen=False)
    return JsonResponse(new_chat_message.body, safe= False)

@login_required(login_url='/login/')
def receivedMessages(request, pk):
    user = request.user
    friend = Friend.objects.get(profile_id=pk)
    profile = Account.objects.get(id=friend.profile.id)
    arr = []
    chats = ChatMessage.objects.filter(msg_sender= profile, msg_receiver= user)
    for chat in chats:
        arr.append(chat.body)
    return JsonResponse(arr, safe= False)

@login_required(login_url='/login/')
def chatNotification(request):
    user = request.user
    friends = user.friends.all()
    arr = []
    for friend in friends:
        chats = ChatMessage.objects.filter(msg_sender__id=friend.profile.id, msg_receiver=user, seen=False)
        arr.append(chats.count())
    return JsonResponse(arr, safe=False)

SajChat/core/templates/core/chat.html
{% extends "base.html" %}


{% block header %}
<div class="header d-flex justify-content-between p-3 align-items-center border-bottom shadow-sm">
    <a class="friend-username" style="font-size: larger; font-weight: bold;"
        href="{% url 'account:view' friend.profile.id %}">{{friend.profile.username}}</a>
    <a class="btn btn-outline-primary" href="{% url 'home' %}" style="border-radius: 100%;">X</a>
</div>
{% endblock header %}


{% block content %}


<div class="row mt-2">
    <div class="col-12">
        <div class="card chat-box h-100" id="chatBox">
            <div class="card-body d-flex flex-column chat-history" id="chat-body" style="height: 330px;">
                {% for chat in chats %}
                {% if chat.msg_sender == user %}
                <div class="message sent">
                    {{chat}}
                </div>
                {% else %}
                <div class="message received">
                    {{chat}}
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<form action="" id="myform" method="POST">
    {% csrf_token %}
    <div class="row my-2" style="padding: 0 15px 0 15px;">
        <div class="col-9" style="padding: 0;">
            {{ form.body }}
        </div>
        <div class="col-3" style="padding: 0;">
            <button class="btn btn-primary btn-block" style="margin: 0;" type="submit" id="submit">Send</button>
        </div>
    </div>
</form>





<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

    let form = document.getElementById("myform")

    form.addEventListener("submit", sendChat)

    function sendChat(e) {
        e.preventDefault()
        let chatMessage = document.getElementById("id_body").value
        const data = { msg: chatMessage };

        async function postJSON(data) {
            try {

                let url = "{% url 'sent_msg' friend.profile.id %}"

                const response = await fetch(url, {
                    method: "POST", // or 'PUT'
                    headers: {
                        "Content-Type": "application/json",
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify(data),
                });
                const result = await response.json();
                var chatBody = document.getElementById('chat-body');
                var messageDiv = document.createElement('div');
                messageDiv.className = 'message sent';
                messageDiv.textContent = result;
                chatBody.appendChild(messageDiv);
                chatBody.scrollTop = chatBody.scrollHeight;
                document.getElementById("id_body").value = ""
            } catch (error) {
                console.error("Error:", error);
            }
        }


        postJSON(data);
    }

    setInterval(receiveMessages, 3000)

    let counter = "{{ count }}"

    function receiveMessages() {

        let url = "{% url 'rec_msg' friend.profile.id %}"

        fetch(url)
            .then(response => response.json())
            .then(data => {
                let lastMsg = "Nothing New"
                if (data.length == 0) { }
                else {
                    let lastMsg = data[data.length - 1]
                    if (counter == data.length) { }
                    else {
                        var chatBody = document.getElementById('chat-body');
                        var messageDiv = document.createElement('div');
                        messageDiv.className = 'message received';
                        messageDiv.textContent = lastMsg;
                        chatBody.appendChild(messageDiv);
                        chatBody.scrollTop = chatBody.scrollHeight;
                    }
                }

                counter = data.length

            })
            .catch((error) => {
                console.error("Error:", error);
            });
    }

    window.onload = function() {
        var chatBody = document.getElementById('chat-body');
        chatBody.scrollTop = chatBody.scrollHeight;
    };


</script>

{% endblock content %}

SajChat/core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

<div class="header d-flex justify-content-between p-3 align-items-center border-bottom shadow-sm">
    <a class="btn btn-outline-primary" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
    <a class="btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
</div>

{% endblock header %}

{% block content %}
<div class="container p-3 border">
    <form class="search-bar justify-content-start " onsubmit="return executeQuery();">
        <input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
        <br>
    </form>
    <div class="chat-list col-12" style="max-height: 300px;">
        {% if friends %}
        {% for friend in friends %}
        <div class="card-body chat-body my-1 user-card justify-content-between row">
            <a class="friend-username" href="{% url 'account:view' friend.profile.id %}">{{ friend }} |
                <span class="msg">0</span>
            </a>
            <a class="btn btn-outline-primary btn-sm" href="{% url 'chat' friend.profile.id %}">Send a Message</a>
        </div>
        {% endfor %}
        {% else %}
        <p> You dont have any Friend. Search, and start your Chat!</p>
        {% endif %}
    </div>
</div>



<script type="text/javascript">
    function executeQuery() {
        var query = document.getElementById("id_q").value
        window.location.replace("{% url 'search' %}?q=" + query)
        return false
    }



    setInterval(getNotification, 2000)


    function getNotification() {
        let url = "{% url 'notification' %}"

        fetch(url)
            .then(res => res.json())
            .then(data => {
                console.log(data)
                let chatNotificationBtn = document.getElementsByClassName("msg")
                for (let i = 0; i < data.length; i++) {
                    chatNotificationBtn[i].innerText = data[i]
                }
            })
            .catch(error => console.log(error))
    }


</script>
{% endblock content %}